<a href="https://colab.research.google.com/github/MridulMalvi/PyTorch-lib/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [ ]:
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(3,5)

tensor([[0.1128, 0.2440, 0.1086, 0.9789, 0.8755],
        [0.4069, 0.5341, 0.7880, 0.8119, 0.9017],
        [0.4815, 0.3823, 0.7666, 0.3685, 0.9519]])

In [ ]:
#generating seed give same randomvalue for same seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#(from,to,jump)
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#to generate x evenly seperated value in a range(from,to,x)
torch.linspace(1,20,10)

tensor([ 1.0000,  3.1111,  5.2222,  7.3333,  9.4444, 11.5556, 13.6667, 15.7778,
        17.8889, 20.0000])

In [ ]:
#diagonal matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#tensor with all same values
torch.full((2,3),4)

tensor([[4, 4, 4],
        [4, 4, 4]])

In [ ]:
#shape
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
#datatype
x.dtype

torch.int64

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.tensor([[2,4,6],[5,9,4]],dtype=torch.int32)

tensor([[2, 4, 6],
        [5, 9, 4]], dtype=torch.int32)

In [ ]:
torch.rand(2,5).dtype

torch.float32

In [ ]:
z=torch.tensor([1.8,5.2,7.8])

In [ ]:
torch.round(z)

tensor([2., 5., 8.])

In [ ]:
torch.floor(z)

tensor([1., 5., 7.])

In [ ]:
torch.ceil(z)

tensor([2., 6., 8.])

In [ ]:
torch.clamp(z,min=2,max=5)

tensor([2., 5., 5.])

In [ ]:
#reduction
a=torch.tensor([[1,9,5],[4,8,4]])

In [ ]:
torch.sum(a)

tensor(31)

In [ ]:
torch.sum(a,dim=0)

tensor([ 5, 17,  9])

In [ ]:
torch.sum(a,dim=1)

tensor([15, 16])

In [ ]:
a=torch.tensor([[1,9,5],[4,8,4]],dtype=torch.float32)

In [ ]:
torch.mean(a)

tensor(5.1667)

In [ ]:
torch.mean(a,dim=0)

tensor([2.5000, 8.5000, 4.5000])

In [ ]:
torch.median(a)

tensor(4.)

In [ ]:
torch.max(a)
torch.min(a)


tensor(1.)

In [ ]:
#give index of max value and min value
torch.argmax(a)
torch.argmin(a)

tensor(0)

In [ ]:
l=torch.tensor([[1,9,5],[4,8,4]])
m=torch.tensor([[2,3],[8,4],[9,4]])

In [ ]:
torch.matmul(l,m)

tensor([[119,  59],
        [108,  60]])

In [ ]:
o=torch.tensor([1,9,5])
p=torch.tensor([2,3,4])

In [ ]:
torch.dot(o,p)

tensor(49)

In [ ]:
m

tensor([[2, 3],
        [8, 4],
        [9, 4]])

In [ ]:
torch.transpose(m,0,1)

tensor([[2, 8, 9],
        [3, 4, 4]])

In [ ]:
o>p

tensor([False,  True,  True])

In [ ]:
o<p

tensor([ True, False, False])

In [ ]:
a=torch.ones(3,4)

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
!cp /content/PyTorch.ipynb /content/PyTorch.ipynb/


cp: cannot stat '/content/PyTorch.ipynb': No such file or directory
